[features]
resolution = true
skip-lint = false

[programs.devnet]
asterlaunch = "ASTRLaunchProgramId11111111111111111111111"

[programs.localnet]
asterlaunch = "ASTRLaunchProgramId11111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "ASTRLaunchProgramId11111111111111111111111"
program = "target/deploy/asterlaunch.so"